### ISSUE TITLE
ERROR: Service 'webui' failed to build

### ISSUE THREAD

**Issue by zarbthomas** [kindlyops/havengrc#585]
When I try to spin up the container it is failing with the following

TypeError: Path must be a string. Received { elm: 'bin/elm' }
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1174:7)
    at module.exports (/code/node_modules/elm/download.js:26:24)
    at Object.<anonymous> (/code/node_modules/elm/install.js:4:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/@babel/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.0 (node_modules/elm-test/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/fork-ts-checker-webpack-plugin/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN daemonite-material@4.1.1 requires a peer of jquery@1.9.1 - 3 but none was installed.
npm WARN daemonite-material@4.1.1 requires a peer of pickadate@^3.5.6 but none was installed.
npm WARN elm-hot-webpack-loader@1.1.8 requires a peer of elm-webpack-loader@^7.0.1 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elm@0.19.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elm@0.19.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-28T20_51_52_528Z-debug.log
The command '/bin/sh -c npm install --quiet' returned a non-zero code: 1
ERROR: Service 'webui' failed to build

**Comment by statik** [comment]
Hi @zarbthomas ! Thanks for trying this out, and reporting the issue. We have had HavenGRC on the shelf for the last year, so it seems likely that the software has gotten dusty and needs some updates to get back up and running.

I likely won't have time to work on this soon, but am definitely interested in learning about any additional details that you are able to figure out and am grateful that you reported the issue.
